### ISSUE TITLE
VideoDecoderSample: Receiving kMediaErrDecode

### ISSUE THREAD

**Issue by lbegue** [SamsungDForum/WebAssemblyDemos#3]
Hi,
I´m having an issue with VideoDecoderSample.
I´m using the emulator for platform tv-samsung-6.0-x86 with GPU on (Cannot launch it with GPU off actually)
Track and source are open without error
AppendPacket is executed many times without error
And then I receive at OnError error code kMediaErrDecode
then track is closed and nothing is displayed but the red background of the initial glClearColor
EMSSSample is runing OK in the same emulator
Could you give me a hint on what could be going wrong?
Thanks

**Comment by abujalski** [comment]
Hello,
Thank you for reporting issue. I've checked sample app, unfortunately rendering video to the texture is not supported on the emulator. On real TV it works as expected. 

The main reason for such situation is that our TVs has specialized video decoder accelerator chip (https://www.kernel.org/doc/Documentation/devicetree/bindings/media/s5p-mfc.txt) which is used for the video decoding.

Sorry for the error reporting as it is indeed confusing, we should fix that. On 6.5 TV Emulator I've got 3 errors reported by the demo:
1. `HTMLMediaElementListener::OnError` is callback called with `kMediaErrDecode` error and empty `error_msg`. It is the same what you've reported
2. `AddTrack` call in `void SamplePlayer::OnSourceClosed()` returns `kTrackLimitReached` error.
3. `ElementaryMediaStreamSourceListener::OnPipelineError` callback is called with `kGeneralError` and `Failed to prepare the pipeline for playback` error message

Unfortunately none of them describes root cause of the problem :(

**Comment by lbegue** [comment]
Thank you for your answer. After that I got a real TV set Samsung T5305 but I still have the same problem, EMSSample is working fine, VideoDecoderSample just performs the red opengl clear, the source is open, the packets are appended but the track is closed and no frame is displayed, FillTextureWithNextFrame is perfomed but the callback is never called.

**Comment by abujalski** [comment]
Hi,
can you please check whether your device supports video texture using following code:

```
auto ver_info = samsung::wasm::EmssVersionInfo::Create()
std::cout << "Supports video_texture: " << ver_info.has_video_texture << "\n";
```

See:
- https://developer.samsung.com/onlinedocs/tv/tizen_wasm_player/classsamsung_1_1wasm_1_1_elementary_media_stream_source.html#a9057d2125dc0dce3b32af121cf64b224
- https://developer.samsung.com/onlinedocs/tv/tizen_wasm_player/structsamsung_1_1wasm_1_1_emss_version_info.html#a53143a0c1faab9e65350ca80874c0a22

**Comment by lbegue** [comment]
Thanks for your answer, you are right, it returns false.
Is there anything I can do to change this? Any configuration or firmware update?

**Comment by abujalski** [comment]
We are providing VideoTexture render target from '21 model onwards and Tizen 6.0. 
See https://developer.samsung.com/smarttv/develop/specifications/tv-model-groups.html

**Comment by lbegue** [comment]
Thank you very much for your time and your help
